import type { FieldType } from "../types";

const firstNames = [
  "Alex",
  "John",
  "Sarah",
  "Michael",
  "David",
  "Emma",
  "Olivia",
  "Daniel",
  "Sophia",
  "James",
];

const lastNames = [
  "Anderson",
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Miller",
  "Wilson",
  "Taylor",
  "Thomas",
  "Martin",
];

const cities = [
  "Kolkata",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Chennai",
];

const states = [
  "West Bengal",
  "Maharashtra",
  "Delhi",
  "Karnataka",
  "Telangana",
  "Tamil Nadu",
];

const companies = [
  "TechNova Solutions",
  "Pixel Labs",
  "CodeCraft Technologies",
  "NextGen Systems",
  "CloudByte",
];

const countries = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
];

function randomItem<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

function randomNumber(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function generatePassword(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";

  return Array.from({ length: 12 }, () =>
    chars.charAt(randomNumber(0, chars.length - 1)),
  ).join("");
}

export function generateFakeData(type: FieldType): string {
  const firstName = randomItem(firstNames);
  const lastName = randomItem(lastNames);

  switch (type) {
    case "firstName":
      return firstName;

    case "lastName":
      return lastName;

    case "fullName":
      return `${firstName} ${lastName}`;

    case "email":
      return `${firstName.toLowerCase()}.${lastName.toLowerCase()}${randomNumber(
        10,
        99,
      )}@example.com`;

    case "phone":
      return `+91 ${randomNumber(7000000000, 9999999999)}`;

    case "username":
      return `${firstName.toLowerCase()}${lastName.toLowerCase()}${randomNumber(
        10,
        99,
      )}`;

    case "password":
      return generatePassword();

    case "address":
      return `${randomNumber(10, 999)} Park Street`;

    case "city":
      return randomItem(cities);

    case "state":
      return randomItem(states);

    case "country":
      return randomItem(countries);

    case "zip":
      return String(randomNumber(700001, 799999));

    case "company":
      return randomItem(companies);

    case "website":
      return "https://example.com";

    case "number":
      return String(randomNumber(1, 100));

    case "date": {
      const date = new Date();

      date.setDate(date.getDate() - randomNumber(0, 365));

      return date.toISOString().split("T")[0];
    }

    case "text":
      return "This is sample test data generated by WebToolKit.";

    default:
      return "Sample test data";
  }
}
