import type { DetectedField, FieldType } from "../types";

const firstNames = [
  "Alex",
  "John",
  "Sarah",
  "Michael",
  "David",
  "Emma",
  "Olivia",
  "Daniel",
  "Sophia",
  "James",
];

const lastNames = [
  "Anderson",
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Miller",
  "Wilson",
  "Taylor",
  "Thomas",
  "Martin",
];

const cities = [
  "Kolkata",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Chennai",
];

const states = [
  "West Bengal",
  "Maharashtra",
  "Delhi",
  "Karnataka",
  "Telangana",
  "Tamil Nadu",
];

const companies = [
  "TechNova Solutions",
  "Pixel Labs",
  "CodeCraft Technologies",
  "NextGen Systems",
  "CloudByte",
];

const countries = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
];

function randomItem<T>(items: T[]): T {
  return items[
    Math.floor(Math.random() * items.length)
  ];
}

function randomNumber(
  min: number,
  max: number,
): number {
  return Math.floor(
    Math.random() * (max - min + 1),
  ) + min;
}

function generatePassword(): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*";

  return Array.from({ length: 12 }, () =>
    chars.charAt(
      randomNumber(0, chars.length - 1),
    ),
  ).join("");
}

export function generateFakeData(
  type: FieldType,
): string {
  const firstName = randomItem(firstNames);
  const lastName = randomItem(lastNames);

  switch (type) {
    case "firstName":
      return firstName;

    case "lastName":
      return lastName;

    case "fullName":
      return `${firstName} ${lastName}`;

    case "email":
      return `${firstName.toLowerCase()}.${lastName.toLowerCase()}${randomNumber(
        10,
        99,
      )}@example.com`;

    case "phone":
      return `+91 ${randomNumber(
        7000000000,
        9999999999,
      )}`;

    case "username":
      return `${firstName.toLowerCase()}${lastName.toLowerCase()}${randomNumber(
        10,
        99,
      )}`;

    case "password":
      return generatePassword();

    case "address":
      return `${randomNumber(
        10,
        999,
      )} Park Street`;

    case "city":
      return randomItem(cities);

    case "state":
      return randomItem(states);

    case "country":
      return randomItem(countries);

    case "zip":
      return String(
        randomNumber(700001, 799999),
      );

    case "company":
      return randomItem(companies);

    case "website":
      return "https://example.com";

    case "number":
      return String(randomNumber(1, 100));

    case "date": {
      const date = new Date();

      date.setDate(
        date.getDate() -
          randomNumber(0, 365),
      );

      return date.toISOString().split("T")[0];
    }

    case "text":
      return "This is sample test data generated by WebToolKit.";

    default:
      return "Sample test data";
  }
}

export function generateSelectValue(
  select: HTMLSelectElement,
): string | null {
  const options = Array.from(
    select.options,
  ).filter(
    (option) =>
      !option.disabled &&
      option.value.trim() !== "",
  );

  if (options.length === 0) {
    return null;
  }

  return randomItem(options).value;
}

export function shouldCheckCheckbox(
  checkbox: HTMLInputElement,
): boolean {
  const text = `
    ${checkbox.name}
    ${checkbox.id}
    ${checkbox.value}
    ${checkbox.getAttribute("aria-label") || ""}
  `.toLowerCase();

  /*
   * Don't automatically agree to things like:
   * terms, conditions, privacy policies.
   */
  if (
    text.includes("terms") ||
    text.includes("condition") ||
    text.includes("privacy") ||
    text.includes("agreement") ||
    text.includes("consent")
  ) {
    return false;
  }

  return true;
}

function dispatchInputEvents(element: HTMLElement): void {
  element.dispatchEvent(new Event("input", { bubbles: true }));
  element.dispatchEvent(new Event("change", { bubbles: true }));
}

function setControlValue(
  element: HTMLInputElement | HTMLTextAreaElement,
  value: string,
): void {
  const prototype =
    element instanceof HTMLTextAreaElement
      ? HTMLTextAreaElement.prototype
      : HTMLInputElement.prototype;
  const descriptor = Object.getOwnPropertyDescriptor(
    prototype,
    "value",
  );

  if (descriptor?.set) {
    descriptor.set.call(element, value);
  } else {
    element.value = value;
  }

  dispatchInputEvents(element);
}

export function fillFields(fields: DetectedField[]): number {
  const elements = Array.from(
    document.querySelectorAll<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >("input, textarea, select"),
  );
  const filledRadioGroups = new Set<string>();
  let filledCount = 0;

  fields.forEach((field) => {
    const element = elements[field.index];

    if (!element) {
      return;
    }

    if (field.type === "radio") {
      const group = element as HTMLInputElement;
      const groupKey = group.name || `radio-${field.index}`;

      if (filledRadioGroups.has(groupKey)) {
        return;
      }

      group.checked = true;
      dispatchInputEvents(group);
      filledRadioGroups.add(groupKey);
      filledCount += 1;
      return;
    }

    if (field.type === "checkbox") {
      const checkbox = element as HTMLInputElement;

      if (shouldCheckCheckbox(checkbox)) {
        checkbox.checked = true;
        dispatchInputEvents(checkbox);
        filledCount += 1;
      }

      return;
    }

    if (field.type === "select") {
      const select = element as HTMLSelectElement;
      const value = generateSelectValue(select);

      if (value !== null) {
        select.value = value;
        dispatchInputEvents(select);
        filledCount += 1;
      }

      return;
    }

    if (
      element instanceof HTMLInputElement ||
      element instanceof HTMLTextAreaElement
    ) {
      setControlValue(element, generateFakeData(field.type));
      filledCount += 1;
    }
  });

  return filledCount;
}
